### ISSUE TITLE
v1.7 Hard crash on Windows when saving

### ISSUE THREAD

**Issue by Warchamp7** [hustlei/QssStylesheetEditor#35]
Running the exe and saving, the program just hard crashes on save with no information

Running the batch file provides a bit more information

```python scripts started.

------------------------
starting...
config file "F:\Program Files\QssStylesheetEditor\scripts\i18n\list.toml" load successed!
config file "F:\Program Files\QssStylesheetEditor\scripts\config\config.toml" load successed!
  Preimporting 'PyQt5.Qsci'   ...   successfully in 0.0045s.
  Preimporting 'res'       ...   successfully in 0.0005s.
  Preimporting 'res.img_rc'   ...   successfully in 0.001s.
  Preimporting 'ui'        ...   successfully in 0.024s.
  Preimporting 'qss_template'   ...   successfully in 0.001s.
coding: ascii
Editor syntax highlighting language: Python
coding: GB2312
Editor syntax highlighting language: QSS
Traceback (most recent call last):
  File "..\src\ui\mainwin.py", line 396, in save
  File "C:\Users\lei\.virtualenvs\QssStylesheetEditor-5KuBu0kK\Lib\site-packages\CodeEditor\editor.py", line 366, in save
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 493-497: character maps to <undefined>
Press any key to continue . . .```

**Comment by hustlei** [comment]
let me see, could i have the file you edited?

**Comment by Warchamp7** [comment]
> let me see, could i have the file you edited?

It was the default file. I opened the program and tried to save

**Comment by hustlei** [comment]
which windows version the program is running on?

**Comment by Warchamp7** [comment]
> which windows version the program is running on?

I'm on Windows 10
