### ISSUE TITLE
Crash:  undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by luzpaz** [hustlei/QssStylesheetEditor#40]
`ImportError: /home/beast/.local/lib/python3.10/site-packages/PyQt5/Qsci.abi3.so: undefined symbol: _ZdlPvm, version Qt_5`

Here's the install log:

```$ pip install QssStylesheetEditor-1.7-py3-none-any.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./QssStylesheetEditor-1.7-py3-none-any.whl
Collecting tomlconfig>=1.2.1
  Downloading tomlconfig-1.2.1-py2.py3-none-any.whl (18 kB)
Collecting CodeEditor>=1.1.0
  Downloading CodeEditor-1.1.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 1.6 MB/s             
Collecting preimport>=1.1.0
  Downloading preimport-1.1.6-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: requests>=2.0 in /usr/lib/python3.10/site-packages (from QssStylesheetEditor==1.7) (2.26.0)
Requirement already satisfied: chardet in /usr/lib/python3.10/site-packages (from CodeEditor>=1.1.0->QssStylesheetEditor==1.7) (4.0.0)
Collecting Qscintilla
  Downloading QScintilla-2.13.1-cp36-abi3-manylinux1_x86_64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 4.5 MB/s            
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.10/site-packages (from requests>=2.0->QssStylesheetEditor==1.7) (3.3)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.10/site-packages (from requests>=2.0->QssStylesheetEditor==1.7) (1.26.7)
Requirement already satisfied: toml in /usr/lib/python3.10/site-packages (from tomlconfig>=1.2.1->QssStylesheetEditor==1.7) (0.10.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/lib/python3.10/site-packages (from Qscintilla->CodeEditor>=1.1.0->QssStylesheetEditor==1.7) (12.9.0)
Requirement already satisfied: PyQt5>=5.15.4 in /usr/lib/python3.10/site-packages (from Qscintilla->CodeEditor>=1.1.0->QssStylesheetEditor==1.7) (5.15.6)
Installing collected packages: Qscintilla, tomlconfig, preimport, CodeEditor, QssStylesheetEditor
Successfully installed CodeEditor-1.1.0 Qscintilla-2.13.1 QssStylesheetEditor-1.7 preimport-1.1.6 tomlconfig-1.2.1
[foo@foo Downloads]$ qss
qsseditor   qssteditor  
[foo@foo Downloads]$ qss
qsseditor   qssteditor  
[foo@foo Downloads]$ qss
qsseditor   qssteditor  
[foo@foo Downloads]$ qsseditor 
starting...
config file "/home/foo/.local/lib/python3.10/site-packages/i18n/list.toml" load successed!
config file "/home/foo/.local/lib/python3.10/site-packages/config/config.toml" load successed!
  Preimporting 'PyQt5.Qsci'   ...   [Error]:Unexpected error happened
  Preimporting 'res'       ...   successfully in 0.0016s.
  Preimporting 'res.img_rc'   ...   successfully in 0.0022s.
  Preimporting 'ui'        ...   [Error]:Unexpected error happened
  Preimporting 'qss_template'   ...   successfully in 0.0023s.
Traceback (most recent call last):
  File "/home/foo/.local/bin/qsseditor", line 8, in <module>
    sys.exit(main())
  File "/home/foo/.local/lib/python3.10/site-packages/app.py", line 47, in main
    App().run()
  File "/home/foo/.local/lib/python3.10/site-packages/app.py", line 37, in run
    from ui.mainwin import MainWin
  File "/home/foo/.local/lib/python3.10/site-packages/ui/__init__.py", line 7, in <module>
    from .mainwinbase import MainWinBase
  File "/home/foo/.local/lib/python3.10/site-packages/ui/mainwinbase.py", line 12, in <module>
    from CodeEditor import Editor
  File "/home/foo/.local/lib/python3.10/site-packages/CodeEditor/__init__.py", line 9, in <module>
    from .editor import Editor
  File "/home/foo/.local/lib/python3.10/site-packages/CodeEditor/editor.py", line 10, in <module>
    from PyQt5 import Qsci
ImportError: /home/foo/.local/lib/python3.10/site-packages/PyQt5/Qsci.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```

### Specs
```
Distributor ID: ManjaroLinux
Release:        21.2.1
Codename:       Qonos
```

Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.1.0) on "xcb" 
OS: Manjaro Linux [linux version 5.15.7-1-rt23-MANJARO]

pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)

**Comment by hustlei** [comment]
For python 3.10 is the newest version, many libs are not compatiable with it. there may be a lib not compatiable exist now

**Comment by luzpaz** [comment]
The challenge of using an Arch derivative distro.

**Comment by artillerymans** [comment]
How does this problem need to be solved

**Comment by luzpaz** [comment]
No idea, never got it solved.

**Comment by artillerymans** [comment]
Is there a way to circumvent it?
