### ISSUE TITLE
运行出现SIP版本号错误

### ISSUE THREAD

**Issue by cdhigh** [hustlei/QssStylesheetEditor#5]
下载 QssStylesheetEditor_v1.5.zip 后运行pyw文件出错：
RuntimeError: the sip module implements API v12.0 to v12.6 but the PyQt5.Qsci module requires API v12.7

我的环境：
OS: Windows7 64bit
Python: 3.7.3 32bit
PyQt5: 5.12.1

Traceback (most recent call last):
  File "E:\Working\Coding\Python\QssStylesheetEditor\installer\..\src\app.py", line 13, in <module>
  File "E:\Working\Coding\Python\QssStylesheetEditor\installer\..\src\ui\__init__.py", line 7, in <module>
  File "E:\Working\Coding\Python\QssStylesheetEditor\installer\..\src\ui\mainwinbase.py", line 12, in <module>
  File "E:\Working\Coding\Python\QssStylesheetEditor\installer\..\src\ui\editor\__init__.py", line 7, in <module>
  File "E:\Working\Coding\Python\QssStylesheetEditor\installer\..\src\ui\editor\editor.py", line 12, in <module>
RuntimeError: the sip module implements API v12.0 to v12.6 but the PyQt5.Qsci module requires API v12.7

**Comment by hustlei** [comment]
我还没有测试过32bit python，64bit python 都测试过，我这几天试一下32bit看看。

看你这个提示的错误，应该是Qsic的版本比PyQt5的版本高了，pip -U PyQt5升级一下PyQt5应该可以。

> 64bit的系统，可以先下载一个绿色版(portable)或者安装板(installer)用

**Comment by cdhigh** [comment]
因为32bit的python兼容性更好，所以我一直都是安装的32bit的。

因为我也是开发者，所以发现此问题就直接提交给你，由你决定是否需要解决。
我知道我升级sip或PyQt5能在本地解决，但是只是决定奇怪，也可能是PyQt5安装程序的问题。

根据提示，是说我的PyQt5版本太高了，sip版本低了，但是我安装PyQt5已经有很长一段时间了，在安装PyQt5之后，重来没有升级过其他部件，所以理论上如果PyQt5需要更高版本的sip，则应该在安装PyQt5时一并提醒需要更新sip或干脆就直接更新了。

**Comment by hustlei** [comment]
好的，非常感谢提交的问题，32bit python3 的问题我肯定都是要完善的

> 有什么问题或建议都欢迎提交^_^
